### ISSUE TITLE
oas2tson - Undesired `$id` prop in inline dereferenced schemas 

### ISSUE THREAD

**Issue by toomuchdesign** [nearform/openapi-transformer-toolkit#179]
Dereferenced nested schemas generated with `oas2tson` come with a redundant [`$id` prop](https://json-schema.org/understanding-json-schema/basics#declaring-a-unique-identifier) which prevent the schema from being successfully registered (eg, with `fastify.addSchema`) because `$id` value collisions.

Given this openAPI definition:
```
components:
  schemas:
    Foo:
      title: Foo
      type: object
      properties:
        bar:
          $ref: '#/components/schemas/Bar'
    Bar:
      title: Bar
      type: string
```
The following `Foo.ts` schema is generated:

```ts
export const Foo = {
  title: "Foo",
  type: "object",
  properties: {
    bar: {
      title: "Bar",
      type: "string",
      $id: "Bar.json" // This prop should not be here
    }
  },
  $id: "Foo.json",
} as const;
```
...In this example the`$id` prop should be probably only assigned to the parent entity.

Original issue:
https://github.com/nearform/openapi-transformer-toolkit/issues/35#issuecomment-1950272145

Repro:
https://github.com/jmjf/oatk-tson-experiment

**Comment by edge33** [comment]
While having resolved `$id` is totally correct for jsonschema refs, we can allow to the generate ts schemas without the `$id` for dereferenced objects using a flag.

I am adding this flag to `openapi-transformer-toolkit` but I have also requested a change to the upstream tool we are using https://github.com/APIDevTools/json-schema-ref-parser/issues/342.


we can monitor this issue and take actions when/if this changes upstream

**Comment by simoneb** [comment]
I'll keep an eye on the referenced issue, but as discussed, let's come up with a client side solution
