### ISSUE TITLE
[oas2ts] Handle complex types

### ISSUE THREAD

**Issue by simoneb** [nearform/openapi-transformer-toolkit#208]
As reported by @toomuchdesign, the underlying library we're using, `json-schema-to-typescript`, has troubles with complex types which are not compiled with the same quality as, e.g. https://github.com/drwpow/openapi-typescript.

As an example it's splitting types across files whereas the latter keeps them in the same one. We should consider improving this, even switching the underlying library to a different one.

**Comment by faizplus** [comment]
won't fix
