### ISSUE TITLE
Why the `[k: string]: unknown` in all the generated types?

### ISSUE THREAD

**Issue by glennsc** [nearform/openapi-transformer-toolkit#25]
Apologies if this was documented and I missed it.

https://github.com/nearform/openapi-transformer-toolkit/blob/27c1d2269dd6b8a99da8dd0657d0569a1f3de126/example/output/types/Address.d.ts#L13

**Comment by simoneb** [comment]
Let's take the chance to better document how to configure this behavior, as the readme only mentions that briefly

**Comment by ilteoood** [comment]
@simoneb it is more related to how you write the OAS, than to this tool.
It's like complaining that a field is generated as optional, without inserting it in the required array 🤔

**Comment by simoneb** [comment]
The ask here is to document how to provide a configuration to the commands, because although the CLI help says you can provide a configuration file, I'm not sure how that exactly works, since the tool we're using doesn't accept a file as a input.

**Comment by ShaunBaker** [comment]
PR open here: https://github.com/nearform/openapi-transformer-toolkit/pull/33
