### ISSUE TITLE
Version 1.4.2 fails to run

### ISSUE THREAD

**Issue by jmjf** [nearform/openapi-transformer-toolkit#283]
## Reproduction

In a project with no `package.json` dependencies for `openapi-transformer-toolkit`, run `npx openapi-transformer-toolkit`.

It fails with an error saying openapi-transformer-toolkit is not found.

## Workaround

`npm i -D openapi-transformer-toolkit@1.4.1` so it runs from a local copy with a safe version.

## Other information

For 1.4.2, [npm](https://www.npmjs.com/package/openapi-transformer-toolkit?activeTab=code) shows the package has only `package.json`, `README.md`, and the `example` directory. The `src` directory and `index.js` are missing.

Version 1.4.1 [npm](https://www.npmjs.com/package/openapi-transformer-toolkit/v/1.4.1?activeTab=code) for comparison.

My npx cache matches what npm reports for both versions.

**Comment by simoneb** [comment]
Thanks for reporting, the issue is most likely caused by the TS migration done in https://github.com/nearform/openapi-transformer-toolkit/pull/216 by @ilteoood. We'll take a look, thanks.

**Comment by ilteoood** [comment]
The migration is ok per se is ok, but seems that while doing so I forgot to add the build step before the publish one. I'll try to do that this weekend.

**Comment by jmjf** [comment]
Thank you for sorting this out. ❤️
