### ISSUE TITLE
How to deal with referenced JSON schemas?

### ISSUE THREAD

**Issue by toomuchdesign** [nearform/openapi-transformer-toolkit#34]
`oas2json` is currently designed to generate referenced JSON schemas. Eg:
```
{
  "type": "array",
  "items": {
    "$ref": "Item.json"
  },
  "title": "List",
  "$id": "List.json"
}
```
...where `Item.json` refers to another local JSON schema file.

Do you have any suggestion about how to dereference the generated JSON schema? Is it something that could fall into the scope of this library?

**Comment by teobmg** [comment]
The fastest way to dereference this is to not have a dedicated object for it.
IMO if you have defined a dedicated object is because you are using it elsewhere, so it's a waste of space to register and parse the same schema multiple times

**Comment by toomuchdesign** [comment]
Hi @teobmg! Let's consider the case where `Item.json` is actually referenced in other object definitions, or where you don't have control over the original OpenApi definition.

I have little experience with JSON schemas, therefore I might be missing some obvious element :)

**Comment by simoneb** [comment]
I'm also not sure why you would need to do this @toomuchdesign ,but I guess we can keep the conversation about this going in #35 , so I'll close this one so we can focus on a single one
